### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by Tindada** [mrcdr/pylanczos#1]
Thank you for your sharing! But I have a problem during installation: when I download the file and run "python setup.py install " , it comes out an error that: 'pylanczos-master\cpp\pylanczos.hpp(6): fatal error C1083: Unable to open including file: “lambda_lanczos.hpp”: No such file or directory' . Do you have any advice for me to fix it?
![微信截图_20220723181759](https://user-images.githubusercontent.com/106970948/180601052-b7d4b7ef-0272-4ffc-9f43-64c0f92fa729.png)

**Comment by mrcdr** [comment]
Thank you for informing about the error. It may be due to submodule dependency of the repository (I should write about it).
Please try either of the following:
(A) If you use pip, you can `pip install pylanczos` without any git cloning (I made this available a few days ago)
(B) Clone the git repository with `--recursive` option. Then `python setup.py install`.

Note: I fixed the code today to support Windows environment correctly. So please clone the latest repository.

**Comment by Tindada** [comment]
> Thank you for informing about the error. It may be due to submodule dependency of the repository (I should write about it). Please try either of the following: (A) If you use pip, you can `pip install pylanczos` without any git cloning (I made this available a few days ago) (B) Clone the git repository with `--recursive` option. Then `python setup.py install`.
> 
> Note: I fixed the code today to support Windows environment correctly. So please clone the latest repository.

Thank you very much! It worked successfully in my huge matrix and help me a lot！

**Comment by mrcdr** [comment]
Thank you too for using my library!
